### ISSUE TITLE
The use of random ports

### ISSUE THREAD

**Issue by anwerett** [Markus-Go/bonesi#27]
Good time of day.
I want to suggest you add the use of random ports.
The fact that the use of only one port, it is somehow not very effective for testing, you need to have a random order.

Example:
tcp 127.0.0.1:80 (only 1 port)
udp 127.0.0.1:80 (only 1 port)
icmp 127.0.0.1:80 (only 1 port) <-- in this Protocol, the ports are not even used, it is necessary to somehow remove all... because if you remove the port from icmp, the script gives an error

To implement this:
tcp 127.0.0.1:+ (use random ports)
udp 127.0.0.1:+ (use random ports)
icmp 127.0.0.1 (no port)

where "+" - random ports on each IP port, or using in order from 0 to 65535

**Comment by Markus-Go** [comment]
Well, actually, source ports are randomized. See min/max port setting in the code for TCP and UDP. Default is a random port between 45534 to 65534. If you want more "randomness", just lower the MIN_PORT setting. Destination ports are of course not randomized, because the botnet attacks a single service. If you want to use BoNeSi for a pure UDP bandwidth attack, you can change the UDP port in bonesi.c, line 301. For TCP, a random destination port doesn't make sense.
